// <auto-generated />
using System;
using DoAnThucTap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnThucTap.Data.Migrations
{
    [DbContext(typeof(DoAnThucTapDbContext))]
    [Migration("20230529064327_themcot")]
    partial class themcot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdQues")
                        .HasColumnType("int");

                    b.Property<bool>("IsSucces")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdQues");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.CategoryNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameCategoryNew")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoryNew");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.CategorySub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountView")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripstion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameCategorySub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pathImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorySub");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdSubject")
                        .HasColumnType("int");

                    b.Property<string>("NameChapter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdSubject");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Comemt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdLesson")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdLesson");

                    b.ToTable("Coment");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdChapter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdChapter");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.MstPerMission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MstPerMission");

                    b.HasData(
                        new
                        {
                            Id = 2003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm câu hỏi",
                            GroupName = "Quản lý câu hỏi",
                            Table = "Answer"
                        },
                        new
                        {
                            Id = 2008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa câu hỏi",
                            GroupName = "Quản lý câu hỏi",
                            Table = "Answer"
                        },
                        new
                        {
                            Id = 2004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa câu hỏi",
                            GroupName = "Quản lý câu hỏi",
                            Table = "Answer"
                        },
                        new
                        {
                            Id = 2002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết câu hỏi",
                            GroupName = "Quản lý câu hỏi",
                            Table = "Answer"
                        },
                        new
                        {
                            Id = 2001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách câu hỏi",
                            GroupName = "Quản lý câu hỏi",
                            Table = "Answer"
                        },
                        new
                        {
                            Id = 3003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm thể loại tin tức",
                            GroupName = "Quản lý thể loại tin tức",
                            Table = "CategoryNew"
                        },
                        new
                        {
                            Id = 3008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa thể loại tin tức",
                            GroupName = "Quản lý thể loại tin tức",
                            Table = "CategoryNew"
                        },
                        new
                        {
                            Id = 3004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa thể loại tin tức",
                            GroupName = "Quản lý thể loại tin tức",
                            Table = "CategoryNew"
                        },
                        new
                        {
                            Id = 3001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách thể loại tin tức",
                            GroupName = "Quản lý thể loại tin tức",
                            Table = "CategoryNew"
                        },
                        new
                        {
                            Id = 4003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "CategorySub"
                        },
                        new
                        {
                            Id = 4008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "CategorySub"
                        },
                        new
                        {
                            Id = 4004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "CategorySub"
                        },
                        new
                        {
                            Id = 4001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "CategorySub"
                        },
                        new
                        {
                            Id = 5003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm chương của bài học",
                            GroupName = "Quản lý chương của bài học",
                            Table = "Chapter"
                        },
                        new
                        {
                            Id = 5008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa chương của bài học",
                            GroupName = "Quản lý chương của bài học",
                            Table = "Chapter"
                        },
                        new
                        {
                            Id = 5004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa chương của bài học",
                            GroupName = "Quản lý chương của bài học",
                            Table = "Chapter"
                        },
                        new
                        {
                            Id = 5002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết chương của bài học",
                            GroupName = "Quản lý chương của bài học",
                            Table = "Chapter"
                        },
                        new
                        {
                            Id = 5001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách chương của bài học",
                            GroupName = "Quản lý chương của bài học",
                            Table = "Chapter"
                        },
                        new
                        {
                            Id = 6003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm bài học",
                            GroupName = "Quản lý bài học",
                            Table = "Lesson"
                        },
                        new
                        {
                            Id = 6008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa bài học",
                            GroupName = "Quản lý bài học",
                            Table = "Lesson"
                        },
                        new
                        {
                            Id = 6004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa bài học",
                            GroupName = "Quản lý bài học",
                            Table = "Lesson"
                        },
                        new
                        {
                            Id = 6002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết bài học",
                            GroupName = "Quản lý bài học",
                            Table = "Lesson"
                        },
                        new
                        {
                            Id = 6001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách bài học",
                            GroupName = "Quản lý bài học",
                            Table = "Lesson"
                        },
                        new
                        {
                            Id = 9003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 7008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 7002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 7001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 9203,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9208,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9204,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9202,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9201,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 8003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm môn học",
                            GroupName = "Quản lý môn học ",
                            Table = "Subject"
                        },
                        new
                        {
                            Id = 8008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa môn học",
                            GroupName = "Quản lý môn học ",
                            Table = "Subject"
                        },
                        new
                        {
                            Id = 8004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa môn học",
                            GroupName = "Quản lý môn học ",
                            Table = "Subject"
                        },
                        new
                        {
                            Id = 8002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết môn học",
                            GroupName = "Quản lý môn học ",
                            Table = "Subject"
                        },
                        new
                        {
                            Id = 8001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách môn học",
                            GroupName = "Quản lý môn học ",
                            Table = "Subject"
                        },
                        new
                        {
                            Id = 9103,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm bài kiểm tra",
                            GroupName = "Quản lý bài kiểm tra",
                            Table = "Test"
                        },
                        new
                        {
                            Id = 9108,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa bài kiểm tra",
                            GroupName = "Quản lý bài kiểm tra",
                            Table = "Test"
                        },
                        new
                        {
                            Id = 9104,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa bài kiểm tra",
                            GroupName = "Quản lý bài kiểm tra",
                            Table = "Test"
                        },
                        new
                        {
                            Id = 9102,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết bài kiểm tra",
                            GroupName = "Quản lý bài kiểm tra",
                            Table = "Test"
                        },
                        new
                        {
                            Id = 9101,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách bài kiểm tra",
                            GroupName = "Quản lý bài kiểm tra",
                            Table = "Test"
                        },
                        new
                        {
                            Id = 1003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1006,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "khóa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1007,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Mở khóa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1005,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Đổi mật khẩu tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        });
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdCategoryNew")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pathImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoryNew");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.PurchasedCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdSub")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdSub");

                    b.HasIndex("IdUser");

                    b.ToTable("purchasedCourses");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quản trị toàn bộ hệ thống",
                            RoleName = "Quản trị hệ thống",
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("MStPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MStPermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1005,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1006,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1007,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 1008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 2001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 2002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 2003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 2004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 2008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 3001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 3003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 3004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 3008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 4001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 4003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 4004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 4008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 5002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 5001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 5003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 5004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 5008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 6002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 6001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 6003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 6004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 6008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 7001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 7002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 7008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 8002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 8001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 8003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 8004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 8008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9001,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9002,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9003,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9004,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9008,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9101,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9102,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9103,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9104,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9108,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9201,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9202,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9203,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9204,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            CreateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MStPermissionId = 9208,
                            RoleId = 1,
                            UpdateAt = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdCategorySub")
                        .HasColumnType("int");

                    b.Property<string>("NameSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorySub");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdLesson")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdLesson");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdRole")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateBy = -1,
                            Gmail = "admin_test@gmail.com",
                            IdRole = 1,
                            PasswordHash = new byte[] { 240, 47, 155, 37, 186, 33, 165, 71, 242, 235, 248, 67, 88, 125, 232, 222, 206, 119, 242, 212, 219, 132, 39, 120, 89, 227, 215, 140, 202, 127, 70, 172, 194, 19, 91, 35, 155, 63, 221, 36, 252, 63, 112, 137, 75, 172, 129, 152, 110, 207, 45, 192, 29, 67, 56, 119, 158, 214, 27, 147, 235, 158, 4, 192 },
                            PasswordSalt = new byte[] { 34, 73, 132, 192, 33, 185, 189, 253, 171, 211, 105, 103, 140, 135, 14, 155, 22, 49, 4, 135, 69, 100, 153, 235, 214, 70, 240, 215, 31, 25, 243, 50, 3, 83, 52, 46, 167, 132, 131, 151, 226, 240, 200, 122, 239, 6, 58, 53, 3, 112, 253, 119, 188, 64, 146, 27, 227, 31, 174, 92, 185, 89, 159, 200, 46, 206, 206, 108, 213, 2, 83, 241, 105, 229, 131, 144, 201, 221, 212, 57, 176, 73, 25, 108, 135, 148, 218, 207, 171, 36, 59, 118, 24, 89, 132, 252, 99, 66, 186, 124, 56, 5, 223, 226, 93, 13, 155, 68, 162, 24, 5, 23, 37, 167, 7, 56, 206, 187, 53, 147, 173, 232, 48, 216, 161, 9, 190, 177 },
                            PhoneNumber = "0928666158",
                            UpdateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Answer", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Test", "test")
                        .WithMany("answers")
                        .HasForeignKey("IdQues");

                    b.Navigation("test");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Chapter", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Subject", "subject")
                        .WithMany("chapters")
                        .HasForeignKey("IdSubject");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Comemt", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Lesson", "lesson")
                        .WithMany("comemts")
                        .HasForeignKey("IdLesson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lesson");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Lesson", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Chapter", "chapter")
                        .WithMany("lessons")
                        .HasForeignKey("IdChapter");

                    b.Navigation("chapter");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.News", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.CategoryNew", "categoryNew")
                        .WithMany("news")
                        .HasForeignKey("IdCategoryNew");

                    b.Navigation("categoryNew");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.PurchasedCourse", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Subject", "subject")
                        .WithMany("purchasedCourses")
                        .HasForeignKey("IdSub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnThucTap.Data.Entites.User", "user")
                        .WithMany("purchasedCourses")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.RolePermission", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.MstPerMission", "mstPerMission")
                        .WithMany("rolePermissions")
                        .HasForeignKey("MStPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnThucTap.Data.Entites.Role", "role")
                        .WithMany("rolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mstPerMission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Subject", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.CategorySub", "categorySub")
                        .WithMany("subjects")
                        .HasForeignKey("IdCategorySub");

                    b.Navigation("categorySub");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Test", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Lesson", "lesson")
                        .WithMany("tests")
                        .HasForeignKey("IdLesson");

                    b.Navigation("lesson");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.User", b =>
                {
                    b.HasOne("DoAnThucTap.Data.Entites.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole");

                    b.Navigation("role");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.CategoryNew", b =>
                {
                    b.Navigation("news");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.CategorySub", b =>
                {
                    b.Navigation("subjects");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Chapter", b =>
                {
                    b.Navigation("lessons");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Lesson", b =>
                {
                    b.Navigation("comemts");

                    b.Navigation("tests");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.MstPerMission", b =>
                {
                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Role", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Subject", b =>
                {
                    b.Navigation("chapters");

                    b.Navigation("purchasedCourses");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.Test", b =>
                {
                    b.Navigation("answers");
                });

            modelBuilder.Entity("DoAnThucTap.Data.Entites.User", b =>
                {
                    b.Navigation("purchasedCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
